"""
rtk.py — The only door to the RTK survey, with the reserved half locked
========================================================================

Implements hard rules **R1** and **R2** of plan v4.

The survey is split by 150 m spatial blocks into a development half and a
RESERVED half. The reserved half exists to be spent exactly once, at the very
end (experiment V3, run by the human), on predictions sealed beforehand.
Every read of it before that moment converts a prediction into a postdiction,
which is why this module is the ONLY loader and why ``allow_reserved``
defaults to False and is meant to be set True by ``experiments/v3_open_reserved.py``
alone — ``tests/test_r1_guard.py`` scans the source tree and fails loudly if
any other file passes it.

ACTA DE ESTADO (2026-08-18, incorporated on adoption of plan v4): the current
reserved partition (seed 20260817, 35 % of blocks, ~57 points) was opened
several times EARLIER THE SAME DAY, before this spec existed — to score
correctors, a censoring rule and the method-B prototypes. Those openings are
recorded in docs/PHASE_LOG.md. Consequence, decided with the user: the guard
is enforced from now on, but any V3 verdict on THIS partition is tainted and
publication-grade claims must rest on the NEW reserved blocks generated by
the V2 campaign designer, which are sealed at creation and have never been
read by anything.

Block assignment is deterministic: blocks of ``block_m`` metres on the
product grid, reserved blocks drawn with ``numpy.random.default_rng(seed)``,
exactly as every experiment of 2026-08-18 did — so dev/reserved membership is
bit-reproducible (R7).
"""

from __future__ import annotations

import numpy as np

#: canonical partition parameters — changing any of these is a NEW partition
#: and must be recorded in docs/PHASE_LOG.md
BLOCK_M = 150.0
HOLDOUT_FRACTION = 0.35
SEED = 20260817

DEFAULT_CSV = "data/villaviciosa_rtk_gnss.csv"
DEFAULT_GRID = "products_villaviciosa/hsr_eot20_2023-2025.tif"


def _assign_blocks(east, north):
    block = (((east - east.min()) // BLOCK_M).astype(int) * 1000
             + ((north - north.min()) // BLOCK_M).astype(int))
    blocks = np.unique(block)
    rng = np.random.default_rng(SEED)
    n_hold = max(2, int(round(HOLDOUT_FRACTION * len(blocks))))
    hold = rng.choice(blocks, n_hold, replace=False)
    return block, np.isin(block, hold)


def load_rtk(csv_path=DEFAULT_CSV, grid_path=DEFAULT_GRID,
             allow_reserved=False):
    """Load the survey mapped onto the canonical grid, DEV ROWS ONLY.

    Returns a dict of aligned arrays: ``row``, ``col`` (grid indices),
    ``elev`` (ellipsoidal heights, metres), ``block`` (block id), ``split``
    ('dev'), plus ``n_reserved_hidden`` so callers can report how much data
    exists without seeing it.

    ``allow_reserved=True`` additionally returns the reserved rows with
    ``split='reserved'``. Only ``experiments/v3_open_reserved.py`` may pass
    it (R1); the test suite enforces this by static scan, and this function
    enforces it dynamically by refusing when the caller is not that script.
    """
    import inspect
    import os
    import pandas as pd
    import rasterio
    from rasterio.warp import transform as rwt

    if allow_reserved:
        caller = inspect.stack()[1].filename.replace("\\", "/")
        if not caller.endswith("experiments/v3_open_reserved.py"):
            raise PermissionError(
                "R1: allow_reserved=True solo puede usarlo "
                "experiments/v3_open_reserved.py, y lo ejecuta el humano. "
                f"Llamante: {caller}")

    df = pd.read_csv(csv_path)
    df = df[df["Solution status"] == "FIX"]
    lon = df["Longitude"].to_numpy(float)
    lat = df["Latitude"].to_numpy(float)
    elev = df["Ellipsoidal height"].to_numpy(float)

    with rasterio.open(grid_path) as s:
        tr, crs, shape = s.transform, s.crs, s.shape
    x, y = rwt("EPSG:4326", crs, lon, lat)
    col = np.floor((np.asarray(x) - tr.c) / tr.a).astype(int)
    row = np.floor((np.asarray(y) - tr.f) / tr.e).astype(int)
    ok = (row >= 0) & (row < shape[0]) & (col >= 0) & (col < shape[1])
    row, col, elev = row[ok], col[ok], elev[ok]

    east = tr.c + (col + 0.5) * tr.a
    north = tr.f + (row + 0.5) * tr.e
    block, is_res = _assign_blocks(east, north)

    def pack(mask, split):
        return {"row": row[mask], "col": col[mask], "elev": elev[mask],
                "block": block[mask],
                "split": np.full(int(mask.sum()), split)}

    dev = pack(~is_res, "dev")
    dev["n_reserved_hidden"] = int(is_res.sum())
    if not allow_reserved:
        return dev
    res = pack(is_res, "reserved")
    return dev, res
